#!/bin/bash

# Runs tests before pushing to remote branch

ENABLED=$(git config --bool hooks.testBeforePush)
if [ "$ENABLED" = "false" ]
then
    # If hook is disabled, quit silently
    exit 0
fi

exec 1>&2

if [[ ! -f Makefile ]]
then
   echo 'No Makefile present, skipping hook'
   exit 0
fi

make -q test &>/dev/null

if [[ $? -eq 2 ]]
then
    echo 'Test target does not exist, skipping hook'
    exit 0
fi

echo 'Running tests...'
make test
