{
  pkgs,
  lib,
  config,
  ...
}:

{
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
  };

  virtualisation.oci-containers.backend = "podman";

  virtualisation.oci-containers.containers."dcgm-exporter" = {
    image = "nvcr.io/nvidia/k8s/dcgm-exporter:4.4.2-4.7.1-ubuntu22.04@sha256:0b98c0aceb106d3eac170bbaf21e70da7bc3a5136991fced511ea1f3dd0022e0";
    ports = [
      "9400:9400/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
    ];
  };

  virtualisation.oci-containers.containers."jellyfin" = {
    image = "lscr.io/linuxserver/jellyfin:latest@sha256:7b29a93a6020f8d5f6c60df381a5ab7d57aa83cda4beb3631bd2bfbbcb1497af";
    environment = {
      "NVIDIA_VISIBLE_DEVICES" = "all";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/mnt/media/movies/:/data/movies:rw"
      "/mnt/media/tv/:/data/tvshows:rw"
      "jellyfin-data:/config:rw"
    ];
    ports = [
      "8096:8096/tcp"
      "8920:8920/tcp"
      "7359:7359/udp"
      "1900:1900/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--device=nvidia.com/gpu=all"
    ];
  };

  systemd.services."podman-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "jellyfin-volume.service"
    ];
    requires = [
      "jellyfin-volume.service"
    ];
    partOf = [
      "podman-compose-beafiboi-root.target"
    ];
    wantedBy = [
      "podman-compose-beafiboi-root.target"
    ];
  };

  systemd.services."jellyfin-volume" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect jellyfin-data || podman volume create jellyfin-data
    '';
    partOf = [ "podman-compose-beafiboi-root.target" ];
    wantedBy = [ "podman-compose-beafiboi-root.target" ];
  };

  systemd.services."podman-dcgm-exporter" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-beafiboi-root.target"
    ];
    wantedBy = [
      "podman-compose-beafiboi-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-beafiboi-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
