services:

  postgres_budgeteer:
    restart: always
    image: bitnami/postgresql:16
    volumes:
      - "{{ postgres_budgeteer_path.path }}:/bitnami/postgresql"
    environment:
      POSTGRESQL_USERNAME: "budgeteer"
      POSTGRESQL_PASSWORD_FILE: /run/secrets/budgeteer_password
      POSTGRESQL_DATABASE: "budgeteer"
    secrets:
      - budgeteer_password
    ports:
      - "54320:5432"
    networks:
      - budgeteer

  pihole:
    restart: always
    image: pihole/pihole:2024.02.0
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "31480:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD_FILE: /run/secrets/pihole_password
    secrets:
      - pihole_password
    volumes:
      - "{{ pihole_path.path }}:/etc/pihole"
      - "{{ dnsmasq_path.path }}:/etc/dnsmasq.d"

  linux-isos:
    restart: always
    image: lscr.io/linuxserver/transmission:2021.11.18
    container_name: transmission
    environment:
      PUID: "1000"
      PGID: "1001"
      TZ: "Etc/UTC"
      WHITELIST: "127.0.0.1,192.168.*.*,"
      HOST_WHITELIST: "*.orangepi.home"
    secrets:
      - transmission_password
    volumes:
      - "{{ transmission_config_path.path }}:/config"
      - "{{ transmission_downloads_path.path }}:/downloads"
      - "{{ transmission_watch_path.path }}:/watch"
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    ports:
      - "9081:8080"
    depends_on:
      miniflux-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
    networks:
      - miniflux

  miniflux-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    networks:
      - miniflux

  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.12
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs

secrets:
  budgeteer_password:
    file: /etc/secrets/budgeteer-password
  pihole_password:
    file: /etc/secrets/pihole-password
  transmission_password:
    file: /etc/secrets/transmission-password

volumes:
  miniflux-db:
  omada-data:
  omada-logs:

networks:
  miniflux:
  transmission:
  omada:
  pihole:
  budgeteer:
