include:
  - compose/pihole.yaml
  - compose/atuin.yaml
  - compose/monitoring.yaml

services:

  postgres_budgeteer:
    restart: always
    image: bitnami/postgresql:16@sha256:233f361c5819c180b600d110d7da953bea6f1a00764752643ffb7b78ba85c628
    volumes:
      - "~/.local/share/postgres/budgeteer:/bitnami/postgresql"
    environment:
      POSTGRESQL_USERNAME: "budgeteer"
      POSTGRESQL_PASSWORD_FILE: /run/secrets/budgeteer_password
      POSTGRESQL_DATABASE: "budgeteer"
    secrets:
      - budgeteer_password
    ports:
      - "54320:5432"
    networks:
      - budgeteer

  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:2.2.10@sha256:ae3a397ca765d9011ce00f2bfeb1f29bf8e6199c38b2883d41ec80f66cd3be50
    restart: unless-stopped
    ports:
      - "127.0.0.1:9081:8080"
    depends_on:
      miniflux-db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://miniflux:secret@miniflux-db/miniflux?sslmode=disable"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "test123"
      RUN_MIGRATIONS: "1"
    dns:
      - 8.8.8.8
    networks:
      - miniflux

  miniflux-db:
    container_name: miniflux-db
    image: postgres:16@sha256:e38a7fe2234174d0eb69b5467d346e1bb193c09f98adc229fc9df30fe364dd4a
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    networks:
      - miniflux

  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.15@sha256:2d631b1aad28e1153234994cb7cf31aa82b728a55e6f87078977649b1a12c9d2
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs

  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:2025.10.4@sha256:449140e073d8d7814098cd62dfdbb326ad043f51a3c4d4721889369f46751d52"
    volumes:
      - "~/.config/home-assistant/:/config"
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:7.0.1@sha256:828c1cd3f957bb0287a099a439505457a25f5d65ed34281acf19cfbf537fe346
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - hass-matter-data:/data

secrets:
  budgeteer_password:
    file: /etc/secrets/budgeteer-password

volumes:
  miniflux-db:
  omada-data:
  omada-logs:
  hass-matter-data:

networks:
  miniflux:
  omada:
  budgeteer:
  normal:
    driver: bridge
