services:

  transmission:
    restart: always
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      PUID: "1000"
      PGID: "1001"
      TZ: "Etc/UTC"
      HOST_WHITELIST: "transmission.home.mishok13.me"
    secrets:
      - transmission_password
    volumes:
      - "~/.local/share/transmission/downloads/:/downloads"
      - "~/.config/transmission/:/config"
      - "~/.local/share/transmission/watch/:/watch"
    ports:
      - "127.0.0.1:9091:9091"
      - "127.0.0.1:51413:51413"
      - "51413:51413/udp"

  sonarr:
    restart: unless-stopped
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: "1000"
      PGID: "1001"
      TZ: "Etc/UTC"
      HOST_WHITELIST: "transmission.home.mishok13.me"
    volumes:
      - "~/.config/sonarr/:/config"
      - "/:/tv" #optional
      - "/path/to/downloadclient-downloads:/downloads" #optional
    ports:
      - 8989:8989

secrets:
  budgeteer_password:
    file: /etc/secrets/budgeteer-password
  pihole_password:
    file: /etc/secrets/pihole-password
  transmission_password:
    file: /etc/secrets/transmission-password

volumes:
  miniflux-db:
  omada-data:
  omada-logs:

networks:
  miniflux:
  transmission:
  omada:
  pihole:
  budgeteer:
