services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"

    volumes:
      - "/mnt/media/movies/:/data/movies"
      - "/mnt/media/tv/:/data/tvshows"
      - "~/.config/jellyfin/:/config"
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:4.0.6-r0-ls256
    container_name: transmission
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
      USER: "admin"
      PASS: "admin"
    volumes:
      - "/mnt/media/downloads/:/downloads"
      - "/mnt/media/transmission/watch/:/watch"
      - "~/.config/transmission/:/config"
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.9.2244-ls255
    restart: unless-stopped
    container_name: sonarr
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
    volumes:
      - "~/.config/sonarr/:/config"
      - "/mnt/media/tv:/tv"
      - "/mnt/media/downloads:/downloads"
    ports:
      - 8989:8989

  radarr:
    image: lscr.io/linuxserver/radarr:5.11.0.9244-ls240
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
    volumes:
      - "~/.config/radarr/:/config"
      - "/mnt/media/movies:/movies"
      - "/mnt/media/downloads:/downloads"
    ports:
      - 7878:7878

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.24.3.4754-ls88
    container_name: prowlarr
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
    volumes:
      - "~/.config/prowlarr:/config"
    ports:
      - 9696:9696
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:24.5.20241227
    container_name: nzbget
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
      NZBGET_USER: "admin"
      NZBGET_PASS: "admin"
    volumes:
      - "~/.config/nzbget:/config"
      - "/mnt/media/downloads:/downloads"
    ports:
      - 6789:6789
    restart: unless-stopped
