# Hardware configuration for bigboi
# Generated by nixos-generate-config on bigboi server
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/762b935f-35dc-45c7-baec-ace90c3e7096";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B441-3959";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/media" = {
    device = "/dev/disk/by-uuid/2859e9fb-fac5-4726-acbd-3e2b4a6126fe";
    fsType = "btrfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/6e2bc576-b0a8-4129-a434-11448078fe91"; }
    {
      device = "/swapfile";
      size = 8192;
    }
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
