mqtt:
  enabled: false

tls:
  enabled: false

cameras:
  bellcam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.250:554/rtsp
          roles:
            - detect
      hwaccel_args: preset-nvidia
      detect:
        enabled: true

detectors:
  onnx:
    type: onnx
