[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = '🅰 '
disabled = true

[kubernetes]
disabled = false
detect_files = ['k8s']

[python]
format = '[${symbol}(${version} )]($style)'

[package]
disabled = true

[git_commit]
tag_disabled = false

[docker_context]
disabled = true

[gcloud]
disabled = true

[directory]
truncate_to_repo = false

[node]
disabled = true
