services:

  atuin:
    container_name: atuin
    restart: always
    image: ghcr.io/atuinsh/atuin:v18.6.1@sha256:869a85bcc169ae9a3ea65dcf32a99dae982d28d8562172e2712d3313d7349203
    command: server start
    volumes:
      - "~/.config/atuin:/config"
    links:
      - atuin-db:db
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://atuin:atuin@db/atuin
      RUST_LOG: info,atuin_server=debug
    networks:
      - atuin

  atuin-db:
    image: postgres:16@sha256:66a5efb5677ffac1037774a0e141fd3a4c035c9c0c0e624c9cc980dfa10f45e5
    restart: always
    volumes:
      - "~/.local/share/postgres/atuin:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "atuin"
      POSTGRES_PASSWORD: "atuin"
      POSTGRES_DB: "atuin"
    networks:
      - atuin

networks:
  atuin:
