services:

  atuin:
    container_name: atuin
    restart: always
    image: ghcr.io/atuinsh/atuin:18.4.0@sha256:8c6fa0aea944bf2a39665c9c69df1c2c0f9c05207bda5b942d450142285e3ee1
    command: server start
    volumes:
      - "~/.config/atuin:/config"
    links:
      - atuin-db:db
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://atuin:atuin@db/atuin
      RUST_LOG: info,atuin_server=debug
    networks:
      - atuin

  atuin-db:
    image: postgres:16@sha256:12c827ab26d9929e1fcf3439ed8f5af8616726d8a605d4dbb010abb797af1821
    restart: always
    volumes:
      - "~/.local/share/postgres/atuin:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "atuin"
      POSTGRES_PASSWORD: "atuin"
      POSTGRES_DB: "atuin"
    networks:
      - atuin

networks:
  atuin:
