services:

  atuin:
    container_name: atuin
    restart: always
    image: ghcr.io/atuinsh/atuin:18.13.6@sha256:9bde3fe6b1633c357cb19c07ea49bb9834720e8ff42d04b39ad7865155581150
    command: start
    volumes:
      - "~/.config/atuin:/config"
    links:
      - atuin-db:db
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://atuin:atuin@db/atuin
      RUST_LOG: info,atuin_server=debug
    networks:
      - atuin

  atuin-db:
    container_name: atuin-db
    image: postgres:18@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
    restart: always
    volumes:
      - "~/.local/share/postgres/atuin:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "atuin"
      POSTGRES_PASSWORD: "atuin"
      POSTGRES_DB: "atuin"
    networks:
      - atuin

networks:
  atuin:
