services:

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:v0.29.0@sha256:9613f2884689b6fad9f1939f6a3b0388c93a022cfaededb19545b329b5c83dea
    restart: always
    container_name: blackbox_exporter
    ports:
      - "127.0.0.1:9115:9115"
