services:
  ollama:
    image: docker.io/ollama/ollama:0.9.0@sha256:2ea3b768a8f2dcd4d910f838d79702bb952089414dd578146619c0a939647ac6
    ports:
      - 11434:11434
    container_name: ollama
    restart: unless-stopped
    environment:
      # - OLLAMA_KEEP_ALIVE=24h
      OLLAMA_HOST: "0.0.0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:0.6.13@sha256:ddc64d14ec933e8c1caf017df8a0068bece3e35acbc59e4aa4971e5aa4176a72
    container_name: ollama-webui
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=test
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=testingwaters
    restart: unless-stopped
