services:
  ollama:
    image: docker.io/ollama/ollama:0.12.9@sha256:889ae74bdb4aa541044574d3e5e5dedde3c682c8b7918b6792aa031e7dfc8f06
    ports:
      - 11434:11434
    container_name: ollama
    restart: unless-stopped
    environment:
      # - OLLAMA_KEEP_ALIVE=24h
      OLLAMA_HOST: "0.0.0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:0.6.34@sha256:98d13c0a9285c110fba9814ef8bfbbaff9250863236fe3a18d29e93534289312
    container_name: ollama-webui
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=test
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=testingwaters
    restart: unless-stopped
