services:

  pihole:
    restart: always
    image: pihole/pihole:2025.11.0@sha256:e28e239f55e648a9d32c8f065650acfe987ddebf1cd5f64f1c071e8716156ceb
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:31480:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      VIRTUAL_HOST: "pihole.mishok13.me"
    secrets:
      - pihole_password
    volumes:
      - "~/.local/share/pihole/:/etc/pihole"
      - "~/.local/share/dnsmasq:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
      - SYS_NICE

secrets:
  pihole_password:
    file: /etc/secrets/pihole-password
