setup:
    uvx --from ansible-core ansible-galaxy install -r requirements.yml

docker-services:
    just play -l server -t docker

packages:
    just play -l server -t apt

caddy:
    just play -l server -t caddy

play *args:
    @mkdir -p .playlogs
    ANSIBLE_LOG_PATH=.playlogs/$(date '+%Y%m%dT%H%M%S').log uvx --from ansible-core ansible-playbook playbooks/playbook.yaml -i inventory.yml -D {{args}}
