setup:
    ansible-galaxy install -r requirements.yml

upgrade:
    ansible-playbook bootstrap/playbook.yaml -t packages

docker-services:
    ansible-playbook playbooks/playbook.yaml -l server -i inventory.yml -D -t docker

packages:
    ansible-playbook playbooks/playbook.yaml -l server -i inventory.yml -D -t apt

caddy:
    ansible-playbook playbooks/playbook.yaml -l server -i inventory.yml -D -t caddy

play *args:
    @mkdir -p .playlogs
    ANSIBLE_LOG_PATH=.playlogs/$(date '+%Y%m%dT%H%M%S').log ansible-playbook playbooks/playbook.yaml -i inventory.yml -D {{args}}
