name: Validate Ansible playbook

on:
  push:
    branches:
      - main
    paths:
      - 'orchestration/**'
  pull_request:
    branches:
      - main
    paths:
      - 'orchestration/**'

permissions: {}

jobs:
  verify-ansible-playbook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./orchestration

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

    - name: Display Ansible and ansible-lint versions
      run: |
        uvx ansible --version
        uvx ansible-lint --version

    - name: Lint it
      run: |
        uvx --from ansible-core ansible-galaxy install -r requirements.yml
        uvx --from ansible-core ansible-playbook --syntax-check playbooks/playbook.yaml
        uvx ansible-lint playbooks/playbook.yaml
