name: Verify Fish Scripts

on:
  push:
    branches:
      - main
    paths:
      - 'home-manager/fish/**'
      - '**/*.fish'
      - '.github/workflows/fish.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'home-manager/fish/**'
      - '**.fish'
      - '.github/workflows/fish.yaml'

permissions: {}

jobs:
  verify-fish-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
      - name: Verify Fish scripts
        run: |
          nix profile install nixpkgs#fish
          find home-manager/fish -name "*.fish" -print0 | while IFS= read -r -d '' file; do
            echo "Checking $file..."
            fish --no-execute "$file"
          done
