name: Verify Nix and Home Manager

on:
  pull_request:
    paths:
      - 'nixos/**'
      - 'home-manager/**'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/nix.yaml'
  push:
    branches: [main]

permissions: {}

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: clydesdale
            type: home-manager
          - target: trakehner
            type: home-manager
          - target: tiniboi
            type: nixos
          - target: beafiboi
            type: nixos
          - target: bigboi
            type: nixos
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.type == 'home-manager' }}
        run: nix run nixpkgs#home-manager -- build --flake .#${{ matrix.target }}
      - if: ${{ matrix.type == 'nixos' }}
        run: nix run nixpkgs#nixos-rebuild -- build --flake .#${{ matrix.target }} --show-trace
