name: zizmor

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@fb9497493b591ad90176d3ecac5ca4aeff8c9faf
